export default [
  {
    value: 'createdAt',
    locale: 'pages.agentPage.calls.columns.createdAt',
    show: true,
    sort: null,
    width: 'minmax(200px, 2fr)',
    field: 'created_at',
  },
  {
    value: 'direction',
    locale: 'pages.agentPage.calls.columns.direction',
    show: true,
    sort: null,
    field: 'direction',
  },
  {
    value: 'answeredAt',
    locale: 'pages.agentPage.calls.columns.answeredAt',
    show: false,
    sort: null,
    field: 'answered_at',
  },
  {
    value: 'bridgedAt',
    locale: 'pages.agentPage.calls.columns.bridgedAt',
    show: false,
    sort: null,
    field: 'bridged_at',
  },
  {
    value: 'queueBridgedAt',
    locale: 'pages.agentPage.calls.columns.queueBridgedAt',
    show: false,
    sort: null,
    field: 'queue_bridged_at',
  },
  {
    value: 'joinedAt',
    locale: 'pages.agentPage.calls.columns.joinedAt',
    show: false,
    sort: null,
    field: 'joined_at',
  },
  {
    value: 'leavingAt',
    locale: 'pages.agentPage.calls.columns.leavingAt',
    show: false,
    sort: null,
    field: 'leaving_at',
  },
  {
    value: 'hangupAt',
    locale: 'pages.agentPage.calls.columns.hangupAt',
    show: false,
    sort: null,
    field: 'hangup_at',
  },
  {
    value: 'reportingAt',
    locale: 'pages.agentPage.calls.columns.reportingAt',
    show: false,
    sort: null,
    field: 'reporting_at',
  },
  {
    value: 'user',
    locale: 'pages.agentPage.calls.columns.user',
    show: false,
    sort: null,
    field: 'user',
  },
  {
    value: 'extension',
    locale: 'pages.agentPage.calls.columns.extension',
    show: false,
    sort: null,
    field: 'extension',
  },
  {
    value: 'from',
    locale: 'pages.agentPage.calls.columns.from',
    show: true,
    sort: null,
    field: 'from',
  },
  {
    value: 'to',
    locale: 'pages.agentPage.calls.columns.to',
    show: true,
    sort: null,
    field: 'to',
  },
  {
    value: 'destination',
    locale: 'pages.agentPage.calls.columns.destination',
    show: true,
    sort: null,
    field: 'destination',
  },
  {
    value: 'gateway',
    locale: 'pages.agentPage.calls.columns.gateway',
    show: false,
    sort: null,
    field: 'gateway',
  },
  {
    value: 'team',
    locale: 'pages.agentPage.calls.columns.team',
    show: false,
    sort: null,
    field: 'team',
  },
  {
    value: 'queue',
    locale: 'pages.agentPage.calls.columns.queue',
    show: true,
    sort: null,
    field: 'queue',
  },
  {
    value: 'member',
    locale: 'pages.agentPage.calls.columns.member',
    show: false,
    sort: null,
    field: 'member',
  },
  {
    value: 'duration',
    locale: 'pages.agentPage.calls.columns.duration',
    show: true,
    sort: null,
    field: 'duration',
  },
  {
    value: 'tags',
    locale: 'pages.agentPage.calls.columns.tags',
    show: false,
    sort: null,
    field: 'tags',
  },
  {
    value: 'display',
    locale: 'pages.agentPage.calls.columns.display',
    show: false,
    sort: null,
    field: 'display',
  },
  {
    value: 'holdSec',
    locale: 'pages.agentPage.calls.columns.holdSec',
    show: false,
    sort: null,
    field: 'hold_sec',
  },
  {
    value: 'waitSec',
    locale: 'pages.agentPage.calls.columns.waitSec',
    show: false,
    sort: null,
    field: 'wait_sec',
  },
  {
    value: 'billSec',
    locale: 'pages.agentPage.calls.columns.billSec',
    show: false,
    sort: null,
    field: 'bill_sec',
  },
  {
    value: 'reportingSec',
    locale: 'pages.agentPage.calls.columns.reportingSec',
    show: false,
    sort: null,
    field: 'reporting_sec',
  },
  {
    value: 'queueWaitSec',
    locale: 'pages.agentPage.calls.columns.queueWaitSec',
    show: false,
    sort: null,
    field: 'queue_wait_sec',
  },
  {
    value: 'queueDurationSec',
    locale: 'pages.agentPage.calls.columns.queueDurationSec',
    show: false,
    sort: null,
    field: 'queue_duration_sec',
  },
  {
    value: 'result',
    locale: 'pages.agentPage.calls.columns.result',
    show: true,
    sort: null,
    field: 'result',
  },
  {
    value: 'sipCode',
    locale: 'pages.agentPage.calls.columns.sipCode',
    show: false,
    sort: null,
    field: 'sip_code',
  },
  {
    value: 'cause',
    locale: 'pages.agentPage.calls.columns.cause',
    show: false,
    sort: null,
    field: 'cause',
  },
];
