export default [
	{
		value: 'createdAt',
		locale: 'pages.card.calls.columns.createdAt',
		show: true,
		sort: null,
		width: '200px',
		field: 'created_at',
	},
	{
		value: 'direction',
		locale: 'pages.card.calls.columns.direction',
		show: true,
		sort: null,
		field: 'direction',
	},
	{
		value: 'answeredAt',
		locale: 'pages.card.calls.columns.answeredAt',
		show: false,
		sort: null,
		field: 'answered_at',
	},
	{
		value: 'bridgedAt',
		locale: 'pages.card.calls.columns.bridgedAt',
		show: false,
		sort: null,
		field: 'bridged_at',
	},
	{
		value: 'queueBridgedAt',
		locale: 'pages.card.calls.columns.queueBridgedAt',
		show: false,
		sort: null,
		field: 'queue_bridged_at',
	},
	{
		value: 'joinedAt',
		locale: 'pages.card.calls.columns.joinedAt',
		show: false,
		sort: null,
		field: 'joined_at',
	},
	{
		value: 'leavingAt',
		locale: 'pages.card.calls.columns.leavingAt',
		show: false,
		sort: null,
		field: 'leaving_at',
	},
	{
		value: 'hangupAt',
		locale: 'pages.card.calls.columns.hangupAt',
		show: false,
		sort: null,
		field: 'hangup_at',
	},
	{
		value: 'reportingAt',
		locale: 'pages.card.calls.columns.reportingAt',
		show: false,
		sort: null,
		field: 'reporting_at',
	},
	{
		value: 'user',
		locale: 'pages.card.calls.columns.user',
		show: false,
		sort: null,
		field: 'user',
	},
	{
		value: 'extension',
		locale: 'pages.card.calls.columns.extension',
		show: false,
		sort: null,
		field: 'extension',
	},
	{
		value: 'from',
		locale: 'pages.card.calls.columns.from',
		show: true,
		sort: null,
		field: 'from',
	},
	{
		value: 'to',
		locale: 'pages.card.calls.columns.to',
		show: true,
		sort: null,
		field: 'to',
	},
	{
		value: 'destination',
		locale: 'pages.card.calls.columns.destination',
		show: true,
		sort: null,
		field: 'destination',
	},
	{
		value: 'gateway',
		locale: 'pages.card.calls.columns.gateway',
		show: false,
		sort: null,
		field: 'gateway',
	},
	{
		value: 'team',
		locale: 'pages.card.calls.columns.team',
		show: false,
		sort: null,
		field: 'team',
	},
	{
		value: 'queue',
		locale: 'pages.card.calls.columns.queue',
		show: true,
		sort: null,
		field: 'queue',
	},
	{
		value: 'member',
		locale: 'pages.card.calls.columns.member',
		show: false,
		sort: null,
		field: 'member',
	},
	{
		value: 'duration',
		locale: 'pages.card.calls.columns.duration',
		show: true,
		sort: null,
		field: 'duration',
	},
	{
		value: 'tags',
		locale: 'pages.card.calls.columns.tags',
		show: false,
		sort: null,
		field: 'tags',
	},
	{
		value: 'display',
		locale: 'pages.card.calls.columns.display',
		show: false,
		sort: null,
		field: 'display',
	},
	{
		value: 'holdSec',
		locale: 'pages.card.calls.columns.holdSec',
		show: false,
		sort: null,
		field: 'hold_sec',
	},
	{
		value: 'waitSec',
		locale: 'pages.card.calls.columns.waitSec',
		show: false,
		sort: null,
		field: 'wait_sec',
	},
	{
		value: 'talkSec',
		locale: 'pages.card.calls.columns.talkSec',
		show: true,
		sort: null,
		field: 'talk_sec',
	},
	{
		value: 'billSec',
		locale: 'pages.card.calls.columns.billSec',
		show: false,
		sort: null,
		field: 'bill_sec',
	},
	{
		value: 'reportingSec',
		locale: 'pages.card.calls.columns.reportingSec',
		show: false,
		sort: null,
		field: 'reporting_sec',
	},
	{
		value: 'queueWaitSec',
		locale: 'pages.card.calls.columns.queueWaitSec',
		show: false,
		sort: null,
		field: 'queue_wait_sec',
	},
	{
		value: 'queueDurationSec',
		locale: 'pages.card.calls.columns.queueDurationSec',
		show: false,
		sort: null,
		field: 'queue_duration_sec',
	},
	{
		value: 'result',
		locale: 'pages.card.calls.columns.result',
		show: true,
		sort: null,
		field: 'result',
	},
	{
		value: 'sipCode',
		locale: 'pages.card.calls.columns.sipCode',
		show: false,
		sort: null,
		field: 'sip_code',
	},
	{
		value: 'cause',
		locale: 'pages.card.calls.columns.cause',
		show: false,
		sort: null,
		field: 'cause',
	},
	{
		value: 'blindTransfer',
		locale: 'pages.shared.columns.blindTransfer',
		show: false,
		sort: null,
		field: 'blind_transfer',
	},
	{
		value: 'scoreRequired',
		locale: 'pages.card.calls.columns.score',
		show: false,
		sort: null,
		field: 'score_required',
	},
	{
		value: 'ratedBy',
		locale: 'pages.card.calls.columns.ratedBy',
		show: false,
		sort: null,
		field: 'rated_by',
	},
];
