export default [
  {
    value: 'queue',
    locale: 'pages.queue.columns.queue',
    show: true,
    sort: null,
    field: 'queue',
  }, {
    value: 'agents',
    locale: 'pages.queue.columns.agents',
    show: true,
    sort: null,
    field: 'agent_status',
    width: '250px',
  },
  // {
  //   value: 'free',
  //   locale: 'pages.queue.columns.free',
  //   show: true,
  //   sort: null,
  //   field: 'agent_status',
  //   width: '120px',
  // },
  // https://webitel.atlassian.net/browse/WTEL-4411
  {
    value: 'team',
    locale: 'pages.queue.columns.team',
    show: true,
    sort: null,
    field: 'team',
  }, {
    value: 'members',
    locale: 'pages.queue.columns.members',
    show: true,
    sort: null,
    field: 'waiting',
    width: '120px',
  }, {
    value: 'count',
    locale: 'pages.queue.columns.activities',
    show: true,
    sort: null,
    field: 'count',
    width: '120px',
  }, {
    value: 'bridged',
    locale: 'pages.queue.columns.bridged',
    show: false,
    sort: null,
    field: 'bridged',
    width: '120px',
  }, {
    value: 'transferred',
    locale: 'pages.queue.columns.transferred',
    show: false,
    sort: null,
    field: 'transferred',
    width: '120px',
  }, {
    value: 'abandoned',
    locale: 'pages.queue.columns.abandoned',
    show: false,
    sort: null,
    field: 'abandoned',
    width: '120px',
  }, {
    value: 'sumBillSec',
    locale: 'pages.queue.columns.sumBillSec',
    show: false,
    sort: null,
    field: 'sum_bill_sec',
    width: '120px',
  }, {
    value: 'avgWrapSec',
    locale: 'pages.queue.columns.avgWrapSec',
    show: false,
    sort: null,
    field: 'avg_wrap_sec',
    width: '120px',
  }, {
    value: 'avgAsaSec',
    locale: 'pages.queue.columns.avgAsaSec',
    show: false,
    sort: null,
    field: 'avg_asa_sec',
    width: '120px',
  }, {
    value: 'avgAwtSec',
    locale: 'pages.queue.columns.avgAwtSec',
    show: false,
    sort: null,
    field: 'avg_awt_sec',
    width: '120px',
  }, {
    value: 'avgAhtSec',
    locale: 'pages.queue.columns.avgAhtSec',
    show: false,
    sort: null,
    field: 'avg_aht_sec',
    width: '120px',
  }, {
    value: 'sl20',
    locale: 'pages.queue.columns.sl20',
    show: false,
    sort: null,
    field: 'sl20',
    width: '120px',
  }, {
    value: 'sl30',
    locale: 'pages.queue.columns.sl30',
    show: false,
    sort: null,
    field: 'sl30',
    width: '120px',
  },
];
