export default [
  {
    value: 'name',
    locale: 'pages.agent.columns.name',
    show: true,
    sort: null,
    field: 'name',
  }, {
    value: 'status',
    locale: 'pages.agent.columns.status',
    show: true,
    sort: null,
    field: 'status',
  }, {
    value: 'statusDuration',
    locale: 'pages.agent.columns.statusDuration',
    show: true,
    sort: null,
    field: 'status_duration',
  }, {
    value: 'team',
    locale: 'pages.agent.columns.team',
    show: true,
    sort: null,
    field: 'team',
  }, {
    value: 'queues',
    locale: 'pages.agent.columns.queues',
    show: true,
    sort: null,
    field: 'queues',
  }, {
    value: 'utilization',
    locale: 'pages.agent.columns.utilization',
    show: true,
    sort: null,
    field: 'utilization',
  }, {
    value: 'callTime',
    locale: 'pages.agent.columns.callTime',
    show: true,
    sort: null,
    field: 'call_time',
  }, {
    value: 'chatTime',
    locale: 'pages.agent.columns.chatTime',
    show: true,
    sort: null,
    field: 'chat_time',
  }, {
    value: 'transferred',
    locale: 'pages.agent.columns.transferred',
    show: true,
    sort: null,
    field: 'transferred',
  }, {
    value: 'abandoned',
    locale: 'pages.agent.columns.abandoned',
    show: true,
    sort: null,
    field: 'abandoned',
  },
];
