import i18n from '@/locale/i18n';

export default [
    {
      text: i18n.t('pages.activeCall.columns.start'),
      value: 'bridgetAt',
      show: true,
      sort: null,
      width: 'minmax(80px, 1fr)',
    },
    {
      text: i18n.t('pages.activeCall.columns.direction'),
      value: 'direction',
      show: true,
      sort: null,
      width: 'minmax(80px, 1fr)',
    },
    {
      text: i18n.t('pages.activeCall.columns.duration'),
      value: 'duration',
      show: true,
      sort: null,
      width: 'minmax(80px, 1fr)',
    },
    {
      text: i18n.t('pages.activeCall.columns.from'),
      value: 'from',
      show: true,
      sort: null,
      width: 'minmax(80px, 1fr)',
    },
    {
      text: i18n.t('pages.activeCall.columns.agent'),
      value: 'agent',
      show: true,
      sort: null,
      width: 'minmax(80px, 1fr)',
    },
    {
      text: i18n.t('pages.activeCall.columns.to'),
      value: 'to',
      show: true,
      sort: null,
      width: 'minmax(80px, 1fr)',
    },
    {
      text: i18n.t('pages.activeCall.columns.destination'),
      value: 'destination',
      show: true,
      sort: null,
      width: 'minmax(80px, 1fr)',
    },
    {
      text: i18n.t('pages.activeCall.columns.extention'),
      value: 'extension',
      show: true,
      sort: null,
      width: 'minmax(80px, 1fr)',
    },
    {
      text: i18n.t('pages.activeCall.columns.queue'),
      value: 'queue',
      show: true,
      sort: null,
      width: 'minmax(80px, 1fr)',
    },
    {
      text: i18n.t('pages.activeCall.columns.result'),
      value: 'state',
      show: true,
      sort: null,
      width: 'minmax(80px, 1fr)',
    },
    {
      text: i18n.t('pages.activeCall.columns.user'),
      value: 'user',
      show: true,
      sort: null,
      width: 'minmax(80px, 1fr)',
    },
    // {
    //   text: i18n.t('pages.activeCall.columns.dtmf'),
    //   value: 'dtmf',
    //   show: true,
    //   sort: null,
    //   width: 'minmax(80px, 1fr)',
    // },
];
