// eslint-disable-next-line no-unused-vars
const queueMock = () => [
        {
            id: 1,
            name: 'queue 1',
            team: 'team 1',
            inbound_calls: 5,
            answer: 0.95,
            abandone: 0.03,
            talk: '00:00:37',
            hold: 2,
            transfer: 3,
            wrap_up_time: 0.42,
            asa: 0.32,
            ldq: 0.5,
            awt: 0.53,
            acwt: 0.66,
            aht: 0.3,
        },
        {
            id: 2,
            name: 'queue 2',
            team: 'team 2',
            inbound_calls: 5,
            answer: 0.95,
            abandone: 0.03,
            talk: '00:00:37',
            hold: 2,
            transfer: 3,
            wrap_up_time: 0.42,
            asa: 0.32,
            ldq: 0.5,
            awt: 0.53,
            acwt: 0.66,
            aht: 0.3,
        },
        {
            id: 3,
            name: 'queue 3',
            team: 'team 3',
            inbound_calls: 5,
            answer: 0.95,
            abandone: 0.03,
            talk: '00:00:37',
            hold: 2,
            transfer: 3,
            wrap_up_time: 0.42,
            asa: 0.32,
            ldq: 0.5,
            awt: 0.53,
            acwt: 0.66,
            aht: 0.3,
        },
        {
            id: 4,
            name: 'queue 4',
            team: 'team 4',
            inbound_calls: 5,
            answer: 0.95,
            abandone: 0.03,
            talk: '00:00:37',
            hold: 2,
            transfer: 3,
            wrap_up_time: 0.42,
            asa: 0.32,
            ldq: 0.5,
            awt: 0.53,
            acwt: 0.66,
            aht: 0.3,
        },
        {
            id: 5,
            name: 'queue 5',
            team: 'team 5',
            inbound_calls: 5,
            answer: 0.95,
            abandone: 0.03,
            talk: '00:00:37',
            hold: 2,
            transfer: 3,
            wrap_up_time: 0.42,
            asa: 0.32,
            ldq: 0.5,
            awt: 0.53,
            acwt: 0.66,
            aht: 0.3,
        },
        {
            id: 6,
            name: 'queue 6',
            team: 'team 6',
            inbound_calls: 5,
            answer: 0.95,
            abandone: 0.03,
            talk: '00:00:37',
            hold: 2,
            transfer: 3,
            wrap_up_time: 0.42,
            asa: 0.32,
            ldq: 0.5,
            awt: 0.53,
            acwt: 0.66,
            aht: 0.3,
        },
        {
            id: 7,
            name: 'queue 7',
            team: 'team 7',
            inbound_calls: 5,
            answer: 0.95,
            abandone: 0.03,
            talk: '00:00:37',
            hold: 2,
            transfer: 3,
            wrap_up_time: 0.42,
            asa: 0.32,
            ldq: 0.5,
            awt: 0.53,
            acwt: 0.66,
            aht: 0.3,
        },
        {
            id: 8,
            name: 'queue 8',
            team: 'team 8',
            inbound_calls: 5,
            answer: 0.95,
            abandone: 0.03,
            talk: '00:00:37',
            hold: 2,
            transfer: 3,
            wrap_up_time: 0.42,
            asa: 0.32,
            ldq: 0.5,
            awt: 0.53,
            acwt: 0.66,
            aht: 0.3,
        },
        {
            id: 9,
            name: 'queue 9',
            team: 'team 9',
            inbound_calls: 5,
            answer: 0.95,
            abandone: 0.03,
            talk: '00:00:37',
            hold: 2,
            transfer: 3,
            wrap_up_time: 0.42,
            asa: 0.32,
            ldq: 0.5,
            awt: 0.53,
            acwt: 0.66,
            aht: 0.3,
        },
        {
            id: 10,
            name: 'queue 10',
            team: 'team 10',
            inbound_calls: 5,
            answer: 0.95,
            abandone: 0.03,
            talk: '00:00:37',
            hold: 2,
            transfer: 3,
            wrap_up_time: 0.42,
            asa: 0.32,
            ldq: 0.5,
            awt: 0.53,
            acwt: 0.66,
            aht: 0.3,
        },
        {
            id: 11,
            name: 'queue 11',
            team: 'team 11',
            inbound_calls: 5,
            answer: 0.95,
            abandone: 0.03,
            talk: '00:00:37',
            hold: 2,
            transfer: 3,
            wrap_up_time: 0.42,
            asa: 0.32,
            ldq: 0.5,
            awt: 0.53,
            acwt: 0.66,
            aht: 0.3,
        },
    ];
