export default [
    {
      text: '',
      value: 'direction',
      show: true,
      sort: null,
      width: 'minmax(15px, 30px)',
    },
    {
      text: 'Call',
      value: 'call',
      show: true,
      sort: null,
      width: 'minmax(100px, 1fr)',
    },
    {
      text: 'Talk',
      value: 'talk',
      show: true,
      sort: null,
      width: 'minmax(66px, 1fr)',
    },
    {
      text: 'Hold',
      value: 'hold',
      show: true,
      sort: null,
      width: 'minmax(60px, 1fr)',
    },
    // {
    //   text: 'Client',
    //   value: 'client',
    //   show: true,
    //   sort: null,
    //   width: 'minmax(120px, 1fr)',
    // },
    {
      text: 'PhoneNumber',
      value: 'phone_number',
      show: true,
      sort: null,
      width: 'minmax(80px, 1fr)',
    },
    {
        text: 'Rating',
        value: 'rating',
        show: true,
        sort: null,
        width: 'minmax(150px, 1fr)',
      },
    // {
    //   text: 'Notes',
    //   value: 'notes',
    //   show: true,
    //   sort: null,
    //   width: 'minmax(60px, 1fr)',
    // },
  ];
