
export default [
    {
      text: 'Queue',
      value: 'name',
      show: true,
      sort: null,
      width: 'minmax(200px, 1fr)',
    },
    {
      text: 'Agents',
      value: 'agents',
      show: true,
      sort: null,
      width: 'minmax(100px, 1fr)',
    },
    {
      text: 'Team',
      value: 'team',
      show: true,
      sort: null,
      width: 'minmax(100px, 1fr)',
    },
    {
      text: 'Members Processing/Waiting',
      value: 'members',
      show: true,
      sort: null,
      width: 'minmax(100px, 1fr)',
    },
    {
      text: 'Inbound Calls',
      value: 'inbound_calls',
      show: true,
      sort: null,
      width: 'minmax(60px, 1fr)',
    },
    {
      text: 'Answer',
      value: 'answer',
      show: true,
      sort: null,
      width: 'minmax(60px, 1fr)',
    },
    {
      text: 'Abandone',
      value: 'abandone',
      show: true,
      sort: null,
      width: 'minmax(60px, 1fr)',
    },
    {
      text: 'Talk',
      value: 'talk',
      show: true,
      sort: null,
      width: 'minmax(60px, 1fr)',
    },
    {
      text: 'Hold',
      value: 'hold',
      show: true,
      sort: null,
      width: 'minmax(60px, 1fr)',
    },
    {
      text: 'Transfer',
      value: 'transfer',
      show: true,
      sort: null,
      width: 'minmax(60px, 1fr)',
    },
    {
      text: 'Wrap up time',
      value: 'wrap_up_time',
      show: true,
      sort: null,
      width: 'minmax(120px, 1fr)',
    },
    {
      text: 'ASA',
      value: 'asa',
      show: true,
      sort: null,
      width: 'minmax(60px, 1fr)',
    },
    {
      text: 'AWT',
      value: 'awt',
      show: true,
      sort: null,
      width: 'minmax(60px, 1fr)',
    },
    {
      text: 'AHT',
      value: 'aht',
      show: true,
      sort: null,
      width: 'minmax(60px, 1fr)',
    },
  ];
