
export default [
    {
      text: 'Queue',
      value: 'queue',
      show: true,
      sort: null,
      width: 'minmax(200px, 1fr)',
    },
    {
      text: 'Agents',
      value: 'agents',
      show: true,
      sort: null,
      width: 'minmax(100px, 1fr)',
    },
    {
      text: 'Team',
      value: 'team',
      show: true,
      sort: null,
      width: 'minmax(100px, 1fr)',
    },
    {
      text: 'Members Processing/Waiting',
      value: 'members',
      show: true,
      sort: null,
      width: 'minmax(100px, 1fr)',
    },
    {
      text: 'Count',
      value: 'count',
      show: true,
      sort: null,
      width: 'minmax(60px, 1fr)',
    },
    {
      text: 'Answer',
      value: 'bridged',
      show: true,
      sort: null,
      width: 'minmax(60px, 1fr)',
    },
    {
      text: 'Abandone',
      value: 'abandoned',
      show: true,
      sort: null,
      width: 'minmax(60px, 1fr)',
    },
    {
      text: 'Talk',
      value: 'sumBillSec',
      show: true,
      sort: null,
      width: 'minmax(60px, 1fr)',
    },
    {
      text: 'Wrap up time',
      value: 'avgWrapSec',
      show: true,
      sort: null,
      width: 'minmax(120px, 1fr)',
    },
    {
      text: 'ASA',
      value: 'avgAsaSec',
      show: true,
      sort: null,
      width: 'minmax(60px, 1fr)',
    },
    {
      text: 'AWT',
      value: 'avgAwtSec',
      show: true,
      sort: null,
      width: 'minmax(60px, 1fr)',
    },
    {
      text: 'AHT',
      value: 'avgAhtSec',
      show: true,
      sort: null,
      width: 'minmax(60px, 1fr)',
    },
  ];
